= Scheduling the Usage Statistics Script
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: tcat, usage, statistics, script

By default, instances of Tcat Server run the Usage Statistics script every thirty minutes. This script sends a randomly generated ID to enable MuleSoft to track the number of Tcat Server administration console instances in use. It does *not* contain any identifying information such as IP addresses, and it does not track the number of Tcat Server agents that are installed (just administration console instances). If you are behind a firewall, this script does not do anything, and it does not generate any errors or disrupt service in any way.

To change or disable this script:

. In the Administration tab in the Tcat Server administration console, click *Utility* in the left-hand navigation pane, and then click *Scheduler*.
. Click *Usage Statistics Job*.
. To change the frequency of the pings (default is every 30 minutes), change the xref:automating-tasks.adoc[cron command], and then click *Save*.
. If you do not want this script to run, click *Delete*.

xref:applying-your-tcat-server-license.adoc[<< Previous: *Applying Your Tcat Server License*]

xref:working-with-logs.adoc[Next: *Working with Logs* >>]