= Working with Server Profiles
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: tcat, server, profiles

A _server profile_ is a set of environment variables and files that you can publish to multiple servers at once. You can use the profile to override variables for the operating system, user, and application on a Tomcat instance. You can also add files from the repository, such as configuration files like `server.xml`. When you add files, you add all files in the workspace you specify. For information on adding workspaces and files to the repository, see xref:managing-the-repository.adoc[Managing the Repository].

*To create or edit a profile:*

. On the Administration tab, click *Server Profiles*, and then click *New*.
. Enter a unique name for the profile and optionally a description.
. Click in the Workspace box and select the workspace that contains the files to add to this profile (see xref:managing-the-repository.adoc[Managing the Repository] for instructions on adding a workspace and files).
. For each file in the workspace, specify which version you want to use, or leave the default "Use Latest" selected.
. To remove the files from this profile, select the *none* workspace.
. To add an environment variable to the profile, click *New Variable*, and then double-click the placeholder name and value and enter the correct information.
. To remove an environment variable from the profile, select it in the table and click *Remove Variable*.
. When you are ready to save the profile and publish its settings and files to all servers that are already set to use this profile, click *Save*. To revert your changes, click *Cancel*.

If a server profile contains any environment variables that affect the startup of Tomcat, you should now restart the Tomcat instances that use that profile by selecting them on the Servers tab and clicking *Restart*.

[WARNING]
====
If you change environment variables outside of Tcat Server and want them to take effect on your Tomcat instance, you must restart Tomcat manually outside of Tcat Server, as Tcat Server uses the environment variables from the current JVM plus those specified in Tcat Server to restart Tomcat.
====

To apply the profile to one or more servers, select the servers on the Servers tab and click *Set Profile*. You can also set the profile when editing a server's details. For more information, see xref:working-with-servers.adoc[Working with Servers].

To remove a profile, select it on the Server Profiles screen and click *Delete*. The environment variables and files on the servers that used that profile will remain intact even after deleting the profile.

xref:integrating-with-ldap.adoc[<< Previous: *Enabling Authentication Through LDAP*]

xref:creating-remote-workspaces.adoc[Next: *Creating Remote Workspaces* >>]